branches:
  only: 
    - master
language: csharp
solution: DocuSign.eSign.sln
mono: latest
sudo: required
dist: trusty
before_install:
 - mkdir -p .nuget
 - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - mono .nuget/nuget.exe restore DocuSign.eSign.sln -Verbosity detailed
  - mono .nuget/nuget.exe install NUnit -Version 3.9.0 -OutputDirectory packages
  - mono .nuget/nuget.exe install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild DocuSign.eSign.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.2
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./tests/DocuSign.eSign.Test/bin/Release/net452/DocuSign.eSign.Test.dll