branches:
  only: 
    - master
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      env: DOTNETCORE=0
    
    - os: linux
      dist: trusty
      mono: none
      dotnet: 2.0.3
      env: DOTNETCORE=1

before_install:
 - mkdir -p .nuget
 - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - |
    if [ "$DOTNETCORE" == "0" ]; then
      mono .nuget/nuget.exe restore DocuSign.eSign.sln -Verbosity detailed
      mono .nuget/nuget.exe install NUnit -Version 3.9.0 -OutputDirectory packages
      mono .nuget/nuget.exe install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
    else
      dotnet restore
    fi
script:
  - |
    if [ "$DOTNETCORE" == "0" ]; then
      msbuild DocuSign.eSign.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.2
      mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./tests/DocuSign.eSign.Test/bin/Release/net452/DocuSign.eSign.Test.dll --where "cat != Manual"
    else
      dotnet test tests/DocuSign.eSign.Test/DocuSign.eSign.Test.csproj -f netcoreapp2.0 -c Release --filter TestCategory!=Manual --no-build
    fi