branches:
  only: 
    - master
language: csharp
solution: DocuSign.eSign.sln
mono: latest
sudo: required
dist: trusty
install:
  - nuget restore DocuSign.eSign.sln -Verbosity detailed
  - nuget install NUnit -Version 3.9.0 -OutputDirectory packages
  - nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild DocuSign.eSign.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.2
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./tests/DocuSign.eSign.Test/bin/Release/net452/DocuSign.eSign.Test.dll